on:
  push:
    branches: [ "react" ]

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: git remote set-url origin https://{secrets.GH_USERNAME}:{secrets.GH_PASSWORD}@github.com/{secrets.GH_USERNAME}/project.git
    - run: yarn install
    - run: yarn run predeploy
    - run: yarn run deploy
